@extends('central.layouts.app', ['title' => 'Activity', 'pageTitle' => 'Activity', 'pageEyebrow' => 'Central administrative audit log'])
@section('content')
<div class="mb-8"><p class="text-sm font-medium text-zinc-500">Auditability</p><h1 class="mt-1 text-3xl font-semibold tracking-tight">Administrative activity</h1><p class="mt-2 text-sm text-zinc-500">Central actions are recorded separately from every tenant database. Tenant deletion cleanup history is retained even after the tenant record is removed.</p></div>

@if($deletionRecords->isNotEmpty())
<section class="mb-6 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900/60"><div><h2 class="font-semibold">Tenant deletion history</h2><p class="mt-1 text-sm text-zinc-500">A durable snapshot of what the application attempted to remove. Failed infrastructure cleanup can be completed manually without losing the original tenant identifiers.</p></div><div class="mt-4 space-y-3">@foreach($deletionRecords as $record)<details class="rounded-xl border border-zinc-200 p-4 dark:border-zinc-800"><summary class="cursor-pointer list-none"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><div class="font-medium">{{ $record->tenant_name ?: $record->tenant_id }} <span class="font-mono text-xs text-zinc-500">{{ $record->tenant_id }}</span></div><div class="mt-1 text-xs text-zinc-500">{{ $record->centralAdmin?->name ?: 'System' }} · {{ $record->completed_at?->format('Y-m-d H:i:s') ?: $record->created_at?->format('Y-m-d H:i:s') }}</div></div><x-ui.status-badge :status="$record->status" /></div></summary><div class="mt-4 grid gap-3 text-xs sm:grid-cols-2"><div><span class="text-zinc-500">Database</span><div class="mt-1 font-mono break-all">{{ $record->database_name ?: '—' }}</div></div><div><span class="text-zinc-500">Platform domain</span><div class="mt-1 font-mono break-all">{{ $record->platform_domain ?: '—' }}</div></div></div>@if(!empty($record->custom_domains))<div class="mt-3 text-xs"><span class="text-zinc-500">Custom domains</span><div class="mt-1 font-mono break-all">{{ implode(', ', $record->custom_domains) }}</div></div>@endif<div class="mt-4 overflow-x-auto"><table class="min-w-full text-xs"><thead><tr class="text-left text-zinc-500"><th class="pb-2 pr-4">Resource</th><th class="pb-2 pr-4">Result</th><th class="pb-2">Target / error</th></tr></thead><tbody class="divide-y divide-zinc-100 dark:divide-zinc-800">@foreach((array) $record->cleanup_results as $resource => $result)<tr><td class="py-2 pr-4 font-mono">{{ $resource }}</td><td class="py-2 pr-4">{{ is_array($result) ? ($result['status'] ?? 'unknown') : 'unknown' }}</td><td class="py-2"><div class="font-mono break-all">{{ is_array($result) ? ($result['target'] ?? '—') : '—' }}</div>@if(is_array($result) && !empty($result['error']))<div class="mt-1 text-red-600">{{ $result['error'] }}</div>@endif</td></tr>@endforeach</tbody></table></div></details>@endforeach</div></section>
@endif

<section class="overflow-hidden rounded-2xl border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900/60"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-zinc-200 text-sm dark:divide-zinc-800"><thead class="bg-zinc-50 text-left text-xs text-zinc-500 dark:bg-zinc-950"><tr><th class="px-5 py-3">When</th><th class="px-5 py-3">Administrator</th><th class="px-5 py-3">Action</th><th class="px-5 py-3">Tenant</th><th class="px-5 py-3">Description</th></tr></thead><tbody class="divide-y divide-zinc-100 dark:divide-zinc-800">@forelse($auditLogs as $log)<tr><td class="whitespace-nowrap px-5 py-4 text-xs text-zinc-500">{{ $log->created_at?->format('Y-m-d H:i:s') }}</td><td class="px-5 py-4">{{ $log->centralAdmin?->name ?: 'System' }}</td><td class="px-5 py-4 font-mono text-xs">{{ $log->action }}</td><td class="px-5 py-4 font-mono text-xs">{{ $log->tenant_id ?: '—' }}</td><td class="px-5 py-4">{{ $log->description ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-zinc-500">No activity recorded.</td></tr>@endforelse</tbody></table></div>@if($auditLogs->hasPages())<div class="border-t border-zinc-200 px-5 py-4 dark:border-zinc-800">{{ $auditLogs->links() }}</div>@endif</section>
@endsection
