<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>@include('partials.head', ['title' => 'Control Center Sign In'])</head>
<body class="min-h-screen bg-zinc-50 text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50">
<div class="grid min-h-screen lg:grid-cols-[minmax(0,1fr)_520px]">
    <section class="hidden bg-zinc-950 p-10 text-white lg:flex lg:flex-col lg:justify-between"><div class="flex items-center gap-3"><div class="flex size-11 items-center justify-center rounded-2xl bg-white text-xs font-semibold text-zinc-950">MT</div><div><div class="font-semibold">{{ config('app.name') }}</div><div class="text-xs text-zinc-400">Central platform administration</div></div></div><div class="max-w-2xl"><div class="text-sm font-medium text-zinc-400">Platform operations</div><h1 class="mt-4 text-4xl font-semibold leading-tight tracking-tight">One control plane for every isolated tenant.</h1><p class="mt-5 max-w-xl leading-7 text-zinc-400">Provision tenant databases and domains, control lifecycle, and review administrative activity without mixing tenant data.</p><div class="mt-8 grid grid-cols-3 gap-3">@foreach([['Tenant isolation','Separate database per tenant'],['Domain control','Permanent hostnames plus aliases'],['Auditability','Central administrative history']] as [$heading,$copy])<div class="rounded-2xl border border-white/10 bg-white/5 p-4"><div class="text-sm font-semibold">{{ $heading }}</div><div class="mt-2 text-xs leading-5 text-zinc-400">{{ $copy }}</div></div>@endforeach</div></div><div class="text-xs text-zinc-500">Restricted to authorized central administrators.</div></section>
    <main class="flex min-h-screen items-center justify-center px-5 py-10 sm:px-8"><div class="w-full max-w-md"><div><p class="text-sm font-medium text-zinc-500">Secure access</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Sign in to the Control Center</h1><p class="mt-3 text-sm leading-6 text-zinc-500">Tenant user accounts cannot access this area.</p></div>@if($errors->any())<div class="mt-6 rounded-xl bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('central.login.store') }}" class="mt-8 space-y-5">@csrf<div><label class="text-sm font-medium" for="email">Email address</label><input id="email" name="email" type="email" value="{{ old('email') }}" required autofocus class="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-3.5 py-3 text-sm dark:border-zinc-700 dark:bg-zinc-900"></div><div><label class="text-sm font-medium" for="password">Password</label><input id="password" name="password" type="password" required class="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-3.5 py-3 text-sm dark:border-zinc-700 dark:bg-zinc-900"></div><button class="w-full rounded-xl bg-zinc-950 px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-zinc-950">Sign in</button></form></div></main>
</div>
</body>
</html>
